version: '3.0'
services:
  mummy:
    image: agileguru/graalvmcloudnativeserver:main
    ports:
      - "8080:8080"
  ankit:
    image: agileguru/graalvmcloudnativeclient:main
    ports:
      - "8888:8888"
    environment:
      - APP_REMOTE_SERVER=http://mummy:8080/server/